### ISSUE TITLE
Extract mode issue

### ISSUE THREAD

**Issue by EvgenKo423** [ncs-sniper/SCS_Unlocker#1]
I've noticed that file/folder modification date/time is not preserved in **Extract** mode regardless of the selected settings. Can you fix it, please?

**Comment by ncs-sniper** [comment]
Thanks for the report. I will correct it this weekend.

**Comment by ncs-sniper** [comment]
Done, at least for files. Date and time of last change is written to both files and directories, but AFAIK time shown for dirs is time of creation, so it has no effect on them. I could write it to time of creation, but even WinRAR does not do that, so I will leave it this way.

**Comment by EvgenKo423** [comment]
Yep, you're right. Thanks!
